version: '3.8'

networks:
  rede_microsservicos:
    external: true

services:
  db:
    container_name: postgres-container
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.2

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.3
    depends_on:
      - db

  controller-cadastro-autenticacao:
    image: jonasrsribeiro/lw-controller-cadastro-autenticacao
    ports:
      - "3334:3334"
    restart: always
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.4
    depends_on:
      - db

volumes:
  postgres-data: