name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Start job
        run: echo "Starting CD pipeline"

  merge_to_prod:
    needs: start
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (if applicable)
        # Add your specific dependency installation command here (e.g., npm install, yarn install)
        # Only if your project requires dependencies during the merge process

      - name: Authenticate to GitHub (restricted scope)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Only fetch the commit that triggered the workflow

      - name: Check if on develop branch
        run: echo ${{ github.ref }}
        if: github.ref == 'refs/heads/develop'

      - name: Merge develop to prod (restricted permissions)
        uses: gr2m/github-actions-merge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN_MERGE }}  # Use a dedicated token with limited permissions
          branch: prod
          squash: false  # Preserve merge history for better traceability (optional)
          commit-message: "Merge develop into prod from CI run [${{ github.sha }}]"