name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Start job
        run: echo "Starting job"

  build_and_deploy:
    needs: start
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build and tag Docker image
        run: |
          docker build -t jonasrsribeiro/lw-controller-cadastro-autenticacao .
          docker tag jonasrsribeiro/lw-controller-cadastro-autenticacao:latest jonasrsribeiro/lw-controller-cadastro-autenticacao:develop

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u jonasrsribeiro --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push jonasrsribeiro/lw-controller-cadastro-autenticacao:latest
          docker push jonasrsribeiro/lw-controller-cadastro-autenticacao:develop

      - name: Merge to prod (somente quando executado na branch develop)
        if: success() && github.ref == 'refs/heads/develop'
        env:
          GHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}  # Certifique-se de ter um token com permissão para merge
        run: |
          git config user.name "jonasrsribeiro"
          git config user.email "jonas.ribeiro01@fatec.sp.gov.br"
          git pull
          git checkout prod  # Alterar para a branch de produção
          git merge develop  # Faz o merge da branch develop na branch prod
