name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Start job
        run: echo "Starting job"

  build_and_deploy:
    needs: start
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"  # Corrigido para uma versão válida do Node.js

      - name: Install dependencies
        run: npm install

      - name: Build and tag Docker image
        run: |
          docker build -t jonasrsribeiro/lw-controller-cadastro-autenticacao .
          docker tag jonasrsribeiro/lw-controller-cadastro-autenticacao:latest jonasrsribeiro/lw-controller-cadastro-autenticacao:develop

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u jonasrsribeiro --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push jonasrsribeiro/lw-controller-cadastro-autenticacao:latest
          docker push jonasrsribeiro/lw-controller-cadastro-autenticacao:develop

      - name: Merge to prod
        if: success() && github.ref == 'refs/heads/develop'
        env:
          GHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
        run: |
          git config user.name "jonasrsribeiro"
          git config user.email "jonas.ribeiro01@fatec.sp.gov.br"

          # Atualizar a branch 'prod' local
          git fetch origin prod
          git checkout origin prod

          # Mesclar 'develop' em 'prod'
          git pull origin prod
          git config pull.rebase false  # Configurar para usar merge
          git merge --no-edit --no-ff develop  # Mesclar 'develop' em 'prod'
          
          # Fazer o push da branch 'prod' atualizada
          git push origin prod