name: CD

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build and tag Docker image
        run: |
          docker build -t jonasrsribeiro/lw-controller-cadastro-autenticacao .
          docker tag jonasrsribeiro/lw-controller-cadastro-autenticacao:latest jonasrsribeiro/lw-controller-cadastro-autenticacao:develop

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u jonasrsribeiro --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push jonasrsribeiro/lw-controller-cadastro-autenticacao:latest
          docker push jonasrsribeiro/lw-controller-cadastro-autenticacao:develop

      - name: Merge to prod
        if: success() && github.ref == 'refs/heads/develop'
        uses: pullreminders/merge-action@v2
        with:
          github_token: ${{ secrets.GHUB_TOKEN }}
          merge_method: 'squash'
          commit_message: 'Merge branch develop into prod'
          commit_author: 'CI Bot <ci@example.com>'
          destination_branch: 'prod'
