name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  # Job inicial sem dependências
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Start job
        # Ação vazia apenas para satisfazer o requisito de um job sem dependências
        run: echo "Starting job"

  # Job principal para build e deploy
  jobs:
  build_and_deploy:
    needs: start
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build and tag Docker image
        run: |
          docker build -t jonasrsribeiro/lw-controller-cadastro-autenticacao .
          docker tag jonasrsribeiro/lw-controller-cadastro-autenticacao:latest jonasrsribeiro/lw-controller-cadastro-autenticacao:develop

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u jonasrsribeiro --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push jonasrsribeiro/lw-controller-cadastro-autenticacao:latest
          docker push jonasrsribeiro/lw-controller-cadastro-autenticacao:develop

      - name: Merge to prod
        if: success() && github.ref == 'refs/heads/develop'
        run: |
          git config user.name "CI Bot"
          git config user.email "ci@example.com"

          # Verificar se a branch 'prod' possui commits
          if [[ $(git rev-list --count origin/prod) -eq 0 ]]; then
            # Se a branch 'prod' estiver vazia, crie um commit inicial
            git checkout -b prod
            git commit --allow-empty -m "Initial commit for prod branch"
            git push origin prod
          fi

          # Atualizar a branch 'prod' com as últimas alterações da branch 'develop'
          git fetch origin prod
          git checkout prod
          git merge --allow-unrelated-histories --squash develop
          git commit -m "Merge branch develop into prod"
          git push origin prod